### ISSUE TITLE
Individual numbers can't receive sms

### ISSUE THREAD

**Issue by douglarek** [alidayu/alidayu-handbook#1]
比如我联通手机号 131 区段；刚开始可以，现在收不到了

**Comment by chaoren1641** [comment]
感谢反馈，明天一早会传达给相关技术人员跟进。

**Comment by woodsrong** [comment]
@douglarek 你好，请提供一下你的淘宝账号，以及短信发送失败的时间点。另外，下次遇到问题可以直接在阿里大鱼官网使用旺旺咨询技术支持同学，会得到更快速的响应

**Comment by douglarek** [comment]
@woodsrong 账号：meican_creative，发送时间：2016-04-11 11:49 AM

**Comment by woodsrong** [comment]
@douglarek hi,douglarek,需要提供接收的手机号码才能进一步查询，为避免手机号码泄露，请到[阿里大鱼官网](http://www.alidayu.com/)向[在线客服](http://service.taobao.com/support/minerva/beta_robot_main.htm?spm=a3142.7791109.a1zln.24.apZQ3n&sourceId=1625164907)提供手机号码查询

**Comment by douglarek** [comment]
Thanks all, now it is OK !
